In [1]:
import pandas as pd
import scanpy as sc

In [2]:
#df_gene = pd.read_csv('./GSE150903/GSE150903_SCT_scaled_count_matrix.txt.gz', sep = ' ', usecols=[0]).T
df = pd.read_csv('./GSE150903/exprMatrix.tsv.gz', sep = '\t', 
                 index_col = 0).T

In [11]:
df_gene = pd.read_csv('./processed_data/clean_data/variable_genes_5k.csv')

In [6]:
df.head()

gene,RP11-34P13.7|RP11-34P13.7,FO538757.2|FO538757.2,AP006222.2|AP006222.2,RP4-669L17.10|RP4-669L17.10,RP5-857K21.4|RP5-857K21.4,RP11-206L10.4|RP11-206L10.4,RP11-206L10.9|RP11-206L10.9,FAM87B|FAM87B,LINC00115|LINC00115,FAM41C|FAM41C,...,APOC2|APOC2,GPR4|GPR4,LINC00895|LINC00895,CTA-243E7.3|CTA-243E7.3,ISX|ISX,TMPRSS6|TMPRSS6,LL22NC03-121E8.3|LL22NC03-121E8.3,DSCR4|DSCR4,LINC00479|LINC00479,TFF2|TFF2
T_AAACCCAAGCTGTTCA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
T_AAACCCACAATTTCTC,0,0,0,0,0,0,2,0,2,0,...,0,0,0,0,0,0,0,0,0,0
T_AAACCCACATTGTCGA,0,1,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
T_AAACCCAGTACGGCAA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
T_AAACCCAGTGTCTTAG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
df.columns = [g.split('|')[0] for g in df.columns]

In [16]:
tmp = set(df_gene.x)
id2gene = [g for g in df.columns if g in tmp]

In [19]:
df_sub = df[id2gene]

In [20]:
df_sub.head()

,SAMD11,HES4,ISG15,AURKAIP1,GABRD,HES5,TTC34,LINC00982,PRDM16,KCNAB2,...,FGL1,CA1,LINC00536,ANKRD22,DMBT1,MYO1A,FRMD6-AS2,GLP2R,CCL4,ST6GALNAC1
T_AAACCCAAGCTGTTCA,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
T_AAACCCACAATTTCTC,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
T_AAACCCACATTGTCGA,1,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
T_AAACCCAGTACGGCAA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
T_AAACCCAGTGTCTTAG,0,0,2,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
df_sub.to_csv('GSE150903_sub.csv')